### ISSUE TITLE
We use the DyNeRF dataset, but an error message appears saying that the json file is missing.

### ISSUE THREAD

**Issue by wkxNiubi** [Linyou/Ced-NeRF#2]
We download the DyNeRF dataset and select the scene cook_spinach. The downloaded content only contains videos from 0 to 20 and poses_bounds.npy, but no json file.
The following is the error：
[Taichi] version 1.7.1, llvm 15.0.4, commit 0f143b2f, linux, python 3.9.19
[Taichi] Starting on arch=cuda
[Taichi] Starting on arch=cuda
/home1/stu/wkx/Ced-NeRF/dataset
Traceback (most recent call last):
  File "/home1/stu/wkx/Ced-NeRF/train_real.py", line 192, in <module>
    train_dataset = SubjectLoader(
  File "/home1/stu/wkx/Ced-NeRF/datasets/dnerf_3d_video_IS.py", line 255, in __init__
    ) = _load_data_from_json(
  File "/home1/stu/wkx/Ced-NeRF/datasets/dnerf_3d_video_IS.py", line 97, in _load_data_from_json
    with open(json_file) as jf:
FileNotFoundError: [Errno 2] No such file or directory: '/home1/stu/wkx/Ced-NeRF/dataset/cook_spinach/images_x4_list.json'

**Comment by wkxNiubi** [comment]
Sincerely ask for your answer！！！
